#!/bin/bash

#cleanup, version 3

#warning:
#-------
#  This script uses quite a number of features that will be explaied
#+ later on.
#  By the time you've finished the first half of book,
#+ there should be nothing mysterius about it. 


LOG_DIR=/var/log
ROOT_UID=0 #Only users with $UID 0 have root privilages.
LINES=50   #Default number of lines saved. 
E_XCD=86   #Can't change directory?
E_NOTROOT=87 #Non-root exit error.

#Run as root,of course.
if [ "$UID" -ne "$UID" ] # Test UID is 0
then 
   echo "Must be root to run this script"
   exit $E_NOROOT
fi

if [ -n "$1"] # Test whether command-line Argument is present and 
              #+ None-empty.
then 
   lines=$1
else 
   lines=$LINES # The default value will be set . 
fi


cd $LOG_DIR
if [ `pwd` != "$LOG_DIR" ] # or if [ "$PWD" != "$LOG_DIR" ]
                           # Not in /var/log?
then
   echo "Can't change to $LOG_DIR"
   exit $E_XCD
fi # Doublecheck if in right directory before missing log file.
tail -n $lies messages > messages.temp   # Save last section of messages log file.
mv messges.tmp messages                  # Rename it as system log 

cat /dev/null > wtmp # Clear wtmp file 
echo "Log files cleand up."
exit 0  # A zero return value from the script upon exit indicates success.
