#!/bin/bash
#Proper header for bash script.

#cleanup, version 2


#Run as root,of course.
#Insert code here to print error message and exit if not root. 

LOG_DIR=/var/log

#Variables are better than hard-coded values.

cd LOG_DIR=/var/log


cat /dev/null > messages
cat /dev/null > wtmp


echo "Log files cleand up."


exit # The right and proper method of "exiting" from a script.
     # A bare "exit" (no prometer) returns the exit status 
     #+ of the preceding command.
